### ISSUE TITLE
"Condition ' _first!=0 ' is true."

### ISSUE THREAD

**Issue by Skyfrit** [arypbatista/godot-swipe-detector#10] opened 2017-01-01 14:37 UTC
When I run my project it works fine but I keep getting these two errors.

![untitled](https://cloud.githubusercontent.com/assets/20874456/21581561/26b20a16-d071-11e6-9751-0cf1242fd92c.jpg)

And I have a Question:
Is it possible to detect only two directions ( left and right )?

**Comment by arypbatista** [comment] 2017-01-04 22:17
On the error, can you specify what are you trying to do? I mean, 

- What specific use of SwipeDetector triggers that error?
- What operative system are you using for building the game?
- Is this an error present when you run your game in a mobile device?

On the question, right now you are able to retrieve the 8 directions from swipe detector (up, up_right, right, down_right, down, down_left, left, up_left). One thing you could do is to use a simple string check to understand if direction is left or right:

```GDScript
func evaluate(gesture):
  if 'left' in gesture.get_direction():  # 3 possibilities: left, up_left, down_left
    # Direction is left
  elif 'right' in gesture.get_direction(): # 3 possibilities: right, up_right, down_right
    # Direction is right
  else:
    # direction is up or down (we couldn't determine weather it is left or right)
```

So you will have 2 blind directions, but you will have 6 directions where you actually know what the user is trying to do. One idea would be to invalidate the 2 blind and just say that you don't have sufficient information to determine whether it was right or left.

These are the areas:

![Swipe areas determining directions](https://raw.githubusercontent.com/arypbatista/godot-swipe-detector/master/examples/swipe-direction/debug-background.png)

Blind gaps are 45º angles on top and bottom:
- Top gap: from 67,5º to 112,5º
- Bottom gap: from 247,5º to 292,5º

There is an [example for directions](https://github.com/arypbatista/godot-swipe-detector/tree/master/examples/swipe-direction) in swipe detector's source that could help you understand what I am saying.

**Comment by Skyfrit** [comment] 2017-01-05 20:55
I am using Windows 10 and Godot Engine 2.1.1 stable
Basically, I just run the project, swipe one or two times and then stop the project, these errors will appear.
I have not tested on my phone yet.

**Comment by arypbatista** [comment] 2017-01-16 03:25
I see the same error on my computer. I will work on it. It is hard to detect where is the issue on the script since there is no traceback (just the engine internal error), but it seems to be an issue related to using a variable whose reference has been recently freed.

**Comment by Skyfrit** [comment] 2017-06-01 10:27
Hi, is there any updates? and it safe to use in a project?

**Comment by arypbatista** [comment] 2017-06-01 16:28
Hi @Skyfrit ! It is safe. I have done a refactoring some months ago after you raised this issue, fixed a couple of code lines that raised warnings on godot debugger. I think the issue is still there, but only on game closing. I will spend more time on tracking this down.

**Comment by arypbatista** [comment] 2019-01-25 00:54
Not an issue on Godot 3.1 Beta 2

**Closed as completed by arypbatista** 2019-01-25 00:54 UTC
Labels: invalid
